// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gstyikqthppkjewcqjrd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdzdHlpa3F0aHBwa2pld2NxanJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ1OTQzMzEsImV4cCI6MjA1MDE3MDMzMX0.21dN2LJ3BYLjqI1MjtAtWNo6tINjo4T_wG_d968oJsQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);